### ISSUE TITLE
esp-scanning.robot tests remove existing OS from boot menu (Windows Boot Manager)

### ISSUE THREAD

**Issue by Psotas** [Dasharo/open-source-firmware-validation#127]
### Device

-

### RTE version

-

### Brief summary

esp-scanning.robot tests remove existing OS from boot menu (Windows Boot Manager)

### How to reproduce

Run esp-scanning.robot tests

### Expected behavior

The tests check the OS can be removed from the boot menu

### Actual behavior

The tests remove the OS from the boot menu

### Link to screenshots or logs

-

**Comment by macpijan** [comment]
this is not the case anymore, we leave ubuntu and windows from dropping
