### ISSUE TITLE
Remove `${ignore_not_found_error}` argument from `Get Index Of Matching Option In Menu`

### ISSUE THREAD

**Issue by Psotas** [Dasharo/open-source-firmware-validation#135]
### The problem you're addressing (if any)

The ${ignore_not_found_error} argument was added unnecessarily

### Describe the solution you'd like

Use `Get Index Of Matching Option In Menu` in https://github.com/Dasharo/open-source-firmware-validation/blob/main/lib/secure-boot-lib.robot#L167

### Additional context

https://github.com/Dasharo/open-source-firmware-validation/pull/118#pullrequestreview-1765009790

**Comment by macpijan** [comment]
The linked code alreedy contains this fix.
