### ISSUE TITLE
`Get Submenu Construction` sometimes returns unexpected construction

### ISSUE THREAD

**Issue by PLangowski** [Dasharo/open-source-firmware-validation#138]
### Device

MSI® PRO Z690-A DDR5

### RTE version

Dasharo v1.1.3

### Brief summary

`Get Submenu Construction` sometimes returns unexpected construction

### How to reproduce

Running `secure-boot.robot`

### Expected behavior

```
Return: ['> TCG Drive Management',
 '> Driver Health Manager',
 '> RAM Disk Configuration',
 '> Secure Boot Configuration',
 '> HDD Security Configuration',
 '> TCG2 Configuration',
 'Press ESC to exit.']
 ```

### Actual behavior

```
Return: ['Devices List                                          Select to manage',
 '> TCG Drive Management',
 '> Driver Health Manager',
 '> RAM Disk Configuration',
 '> Secure Boot Configuration',
 '> HDD Security Configuration',
 '> TCG2 Configuration',
 'Press ESC to exit.']
 ```

### Link to screenshots or logs

![image](https://github.com/Dasharo/open-source-firmware-validation/assets/105967771/c1774d0f-368c-450b-9327-57069687d4c6)

### Additional context

This issue is similar to https://github.com/Dasharo/open-source-firmware-validation/issues/119

**Comment by macpijan** [comment]
@BeataZdunczyk Another one that may need adding some stress/stability test to narrow down the problem and monitor reliability of framework.

I am starting adding such label.

**Comment by JanPrusinowski** [comment]
This issue did not replicate on qemu: 
[log.zip](https://github.com/user-attachments/files/16424154/log.zip)
I have run a test which reads menu construction 50 times and it didn't fail even once. I am going to test it on the MSI® PRO Z690-A DDR5 to see if the error still occurs.

**Comment by JanPrusinowski** [comment]
I have managed to replicate this issue.
[log.zip](https://github.com/user-attachments/files/16427144/log.zip)
![image](https://github.com/user-attachments/assets/e6a53b69-3ba9-4d33-9836-413f333c5f48)

**Comment by JanPrusinowski** [comment]
I have added a delay in Get Menu Construction and it lokks like it fixed the issue.
200 repeats and issue didnt replicate even once:
[log.zip](https://github.com/user-attachments/files/16437073/log.zip)

**Comment by macpijan** [comment]
Thanks @JanPrusinowski I have merged it, let's see if that solves it in the long run as well.
