### ISSUE TITLE
Use `Skip If    not ${some_flag}    ${TEST_NAME.split()}[0] not supported`

### ISSUE THREAD

**Issue by Psotas** [Dasharo/open-source-firmware-validation#157]
### The problem you're addressing (if any)

This solution will allow us to avoid typos that in `skip if` we have a test number that does not match the actual one.

### Describe the solution you'd like

Use `Skip If    not ${some_flag}    ${TEST_NAME.split()}[0] not supported`

**Comment by macpijan** [comment]
This has been somehow improved in another way via: https://github.com/Dasharo/open-source-firmware-validation/commit/e4a162fe8b427089e304bd4879c54676dd03c18d
