### ISSUE TITLE
Tests fail due to missing packages

### ISSUE THREAD

**Issue by mkopec** [Dasharo/open-source-firmware-validation#195]
### Device

NovaCustom NS70MU

### RTE version

n/a

### Affected component(s) or functionality

Wi-Fi / BT tests

### Brief summary

Wi-Fi / BT tests fail due to missing `lspci` package

### How reproducible

100%

### How to reproduce

- install ubuntu 22.04
- start running tests on a clean installation

### Expected behavior

tests install all missing utils automatically

### Actual behavior

tests fail because `lspci` is missing

### Link to screenshots or logs

![image](https://github.com/Dasharo/open-source-firmware-validation/assets/3678707/dbd4d436-c0fa-490e-bef7-84df9ab7cd59)

### Solutions you've tried

- don't depend on lspci?
- take care of installing all utilities in suite setup. `ethtool` is also not installed OOTB, so warmboot tests using WoL fail.

**Comment by mkopec** [comment]
another one: `fwts` in `SUSP005.002`

**Comment by macpijan** [comment]
@artur-rs this would be trivial fix

**Comment by JanPrusinowski** [comment]
PR dostepny: https://github.com/Dasharo/open-source-firmware-validation/pull/297
