### ISSUE TITLE
SD card reader tests can't find SD card on NS70MU

### ISSUE THREAD

**Issue by mkopec** [Dasharo/open-source-firmware-validation#197]
### Device

NovaCustom NS70MU

### RTE version

n/a

### Affected component(s) or functionality

SD card reader tests

### Brief summary

SD card reader tests only look for `sdX` devices (sda, sdb etc). This is invalid for most builtin SD card readers which enumerate SD cards as `mmcblkX`

### How reproducible

100%

### How to reproduce

run `SDC001.001` on NS70MU

### Expected behavior

test finds the inserted SD card

### Actual behavior

test fails despite a card being inserted

### Link to screenshots or logs

![image](https://github.com/Dasharo/open-source-firmware-validation/assets/3678707/7525aec5-6336-487e-a479-ab22bbedb284)

### Additional context

Test also looks for a specific device name, ideally it wouldn't depend on that

`SD card read/write` tests already work fine

**Comment by filipleple** [comment]
Issue resolved by [this](https://github.com/Dasharo/open-source-firmware-validation/pull/294) PR. 

Log available [here](https://cloud.3mdeb.com/index.php/s/RFeQTKXpD8wkyo2).
