### ISSUE TITLE
Add https check to network-boot test

### ISSUE THREAD

**Issue by filipleple** [Dasharo/open-source-firmware-validation#200]
### The problem you're addressing (if any)

The [network-boot](https://github.com/Dasharo/open-source-firmware-validation/blob/0d1b25c3cdd4d73d651972fc28e22fdd1be2ae54/dasharo-compatibility/network-boot.robot#L4) test does not verify whether connection to boot server is established via the http-secure protocol

### Describe the solution you'd like

Add verification that we use https not http

**Comment by krystian-hebel** [comment]
https://github.com/Dasharo/open-source-firmware-validation/pull/300 was merged, closing.
