### ISSUE TITLE
`uefi-password.robot`  AttributeError: 'list' object has no attribute 'encode'

### ISSUE THREAD

**Issue by Psotas** [Dasharo/open-source-firmware-validation#218]
### Device

VP4650

### RTE version

Dasharo v1.2.0

### Brief summary

PSW002.001 Password setting mechanism correctness checking :: This... | FAIL | AttributeError: 'list' object has no attribute 'encode'

### How to reproduce

robot -L TRACE -v rte_ip:192.168.10.203 -v config:protectli-vp4650 -v device_ip:192.168.10.21 dasharo-security/uefi-password.robot 

### Expected behavior

PASS

### Actual behavior

AttributeError: 'list' object has no attribute 'encode'

### Link to screenshots or logs

[log-uefi-password.zip](https://github.com/Dasharo/open-source-firmware-validation/files/14538655/log-uefi-password.zip)

**Comment by macpijan** [comment]
@Psotas Please check this commit: e144bcbf523f1c27231c15e0a4c68663e54970cc

**Comment by Psotas** [comment]
@macpijan 
It is works.
I also improve teardown in commit.
[log-teardown-fixed.zip](https://github.com/Dasharo/open-source-firmware-validation/files/14555739/log-teardown-fixed.zip)
