### ISSUE TITLE
ESP tests should check if there are no "(on Non-Block Boot Device)" in detected entries

### ISSUE THREAD

**Issue by macpijan** [Dasharo/open-source-firmware-validation#224]

**Comment by WiktorG351** [comment]
Does this impact the results of the tests at all (and could it)?
Or is this issue related more to the logic of the test cases/keywords?
A small description would be very helpful

**Comment by WiktorG351** [comment]
@macpijan [new PR](https://github.com/Dasharo/open-source-firmware-validation/pull/278) added such a test
