### ISSUE TITLE
APU tests fail with: "No keyword with name 'Flash Apu' found."

### ISSUE THREAD

**Issue by pkubaj** [Dasharo/open-source-firmware-validation#239]
### Device

APU3

### RTE version

1.1.0

### Brief summary

No keyword with name 'Flash Apu' found.

### How to reproduce

Run any test for APU.

### Expected behavior

Tests should start.

### Actual behavior

Test fail because of missing keyword.

### Link to screenshots or logs

[dasharo-compatibility_debug.log](https://github.com/Dasharo/open-source-firmware-validation/files/14701126/dasharo-compatibility_debug.log)

**Comment by mkopec** [comment]
`Flash Apu` kwd added in https://github.com/Dasharo/open-source-firmware-validation/pull/237/commits/573111eb4dcd728b76c1a1c161a021e7b00f2aee
