### ISSUE TITLE
APU: Option Secure Boot Mode not found in the list

### ISSUE THREAD

**Issue by pkubaj** [Dasharo/open-source-firmware-validation#247]
### Device

APU2

### RTE version

1.1.0

### Brief summary

APU: Option Secure Boot Mode not found in the list

### How to reproduce

Try executing SBO* tests.

### Expected behavior

Tests should run.

### Actual behavior

Option Secure Boot Mode not found in the list

### Link to screenshots or logs

![image](https://github.com/Dasharo/open-source-firmware-validation/assets/4457924/50623ef5-3670-4ac5-b29a-1fab7c497d60)

**Comment by miczyg1** [comment]
The test simply did not enter Secure Boot menu and stayed in Device Manager. According to logs the Device Manager has the Secure Boot Configuration on the list, but somehow the test failed to enter it.

So it is some bug in test, not in the firmware.

**Comment by PLangowski** [comment]
The following problems appeared:

- The `Reenter menu ...` keyword sometimes returns the previous menu's construction despite the fact that it did reenter the menu.
- Sometimes APU reads the  `Secure Boot Configuration` menu title as an option, which breaks the next steps. 

As for the first bug, I'm attaching logs from a fail and pass.

[log-fail.txt](https://github.com/user-attachments/files/15800884/log-fail.txt)
[log-pass.txt](https://github.com/user-attachments/files/15800883/log-pass.txt)
ed construction

**Comment by PLangowski** [comment]
@macpijan As I've mentioned in https://github.com/Dasharo/open-source-firmware-validation/pull/273, the problem no longer appears on the `develop` branch. I am closing that PR. I added `Reenter Menu` keyword tests here: https://github.com/Dasharo/open-source-firmware-validation/pull/329
