### ISSUE TITLE
No Read Firmware keyword breaks DMI002.001 on APU

### ISSUE THREAD

**Issue by pkubaj** [Dasharo/open-source-firmware-validation#252]
### Device

APU2

### RTE version

1.1.0

### Brief summary

No Read Firmware keyword breaks DMI002.001 on APU

### How to reproduce

`robot -b command_log.txt -v snipeit:no -L TRACE -v rte_ip:192.168.10.172 -v device_ip:192.168.10.36 -v config:pcengines-apu2 -t DMI002.001* dasharo-compatibility/dmidecode.robot`

### Expected behavior

Test should pass.

### Actual behavior

`No keyword with name 'Read Firmware' found. Did you try using keyword 'SSHLibrary.Read' or 'Telnet.Read' and forgot to use enough whitespace between keyword and arguments?
`

### Link to screenshots or logs

[command_log.txt](https://github.com/Dasharo/open-source-firmware-validation/files/14806064/command_log.txt)

**Comment by artur-rs** [comment]
@pkubaj in the meantime, you can confirm that the linked PR resolves the problem
