### ISSUE TITLE
Debian not detected in scripts/secure-boot/generate-images/sb-img-wrapper.sh

### ISSUE THREAD

**Issue by pkubaj** [Dasharo/open-source-firmware-validation#254]
### Device

APU2

### RTE version

1.1.0

### Brief summary

Debian not detected in scripts/secure-boot/generate-images/sb-img-wrapper.sh

### How to reproduce

```
debian@debian:~/open-source-firmware-validation/scripts/secure-boot/generate-images$ ./sb-img-wrapper.sh 
```

### Expected behavior

Debian should be detected.

### Actual behavior

```
Creating image for INTERMEDIATE 

Installing dependencies
Unknown Package Manager
debian@debian:~/open-source-firmware-validation/scripts/secure-boot/generate-images$ lsb_release -is
No LSB modules are available.
Debian
```

### Link to screenshots or logs

There are no logs.

**Comment by macpijan** [comment]
Related to: https://github.com/Dasharo/open-source-firmware-validation/issues/256

**Comment by artur-rs** [comment]
PR with fixes has been merged, closing
