### ISSUE TITLE
Unable to locate package sbsigntools

### ISSUE THREAD

**Issue by pkubaj** [Dasharo/open-source-firmware-validation#255]
### Device

APU2

### RTE version

1.1.0

### Brief summary

Unable to locate package sbsigntools when running sb-img-wrapper.sh

### How to reproduce

`./sb-img-wrapper.sh`

### Expected behavior

Tools should be installed and script should proceed.

### Actual behavior

```
Creating image for INTERMEDIATE 

Installing dependencies
Detected Package Manager: apt
Detected Distro: Debian
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package sbsigntools
Cannot install sbsigntools faketime : (100)
```

### Link to screenshots or logs

There ane no logs.

**Comment by pkubaj** [comment]
This issue happens when I force using apt in `generate-image.sh` as otherwise Debian is not detected.

**Comment by pkubaj** [comment]
Package name is changed to `sbsigntool`.

**Comment by BeataZdunczyk** [comment]
> This issue happens when I force using apt in generate-image.sh as otherwise Debian is not detected.

_Debian_? Do you mean Ubuntu @pkubaj?

**Comment by pkubaj** [comment]
No, Debian, since that's what's installed on the VM.

**Comment by macpijan** [comment]
Related to: https://github.com/Dasharo/open-source-firmware-validation/issues/256
