### ISSUE TITLE
Temperature detection and reporting should be reworked

### ISSUE THREAD

**Issue by pkubaj** [Dasharo/open-source-firmware-validation#281]
### Device

Any

### RTE version

1.10

### Brief summary

Temperature detection and reporting should be reworked

### How to reproduce

Try running CPT tests.

### Expected behavior

CPT tests should not return failure when the temperature is almost all the time ok.

### Actual behavior

CPT tests detect and report the current temperature and return fail when it's too high even when there are only temporary spikes.

### Link to screenshots or logs

I don't have logs.

**Comment by tym2k1** [comment]
Already addressed by https://github.com/Dasharo/open-source-firmware-validation/commit/9b50c95d93ac9b0f8501080044c5a4930cb8f2fa
