### ISSUE TITLE
Multiple automatic tests go into wrong submenu in firmware

### ISSUE THREAD

**Issue by johanes2115** [Dasharo/open-source-firmware-validation#36]
Dasharo Security: UEFI Secure Boot test opens TCG Configuration submenu.
Dasharo Security: ME neuter/disable test opens Power Management Options submenu.
Dasharo Security: Network Boot availability test opens One Time Boot submenu.
Dasharo Security: USB stack test opens Networking Options submenu.
Dasharo Security: BIOS lock support test opens Networking Options submenu.
Dasharo Security: SMM BIOS write protection test opens Networking Options submenu.
Dasharo Security: Early Boot DMA protection test opens Intel Management Engine Options submenu.
Tested on Novacustom nv41 ADL. Branch `novacustom-wip`.

**Comment by macpijan** [comment]
@johanes2115 Please include revision of test environment and logs when reporting problems. Otherwise it would be more challenging to classify and fix them.

**Comment by johanes2115** [comment]
@macpijan newest commit where mentioned problems occur: 8a21d7f4301f9323f830d6e8f7827c17af3c6410
[wrong_submenu_tests.zip](https://github.com/Dasharo/open-source-firmware-validation/files/12891962/wrong_submenu_tests.zip)

**Comment by Psotas** [comment]
Dasharo Security: UEFI Secure Boot test on VP4670 v2
The keyword `Secure Boot Configuration Submenu` opens the `Driver Health Manager` submenu
[secure-boot_log.zip](https://github.com/Dasharo/open-source-firmware-validation/files/12913237/secure-boot_log.zip)

**Comment by Psotas** [comment]
Same issue on VP2420:
[reset-to-defaults_log.zip](https://github.com/Dasharo/open-source-firmware-validation/files/13164219/reset-to-defaults_log.zip)
[bios-lock_log.zip](https://github.com/Dasharo/open-source-firmware-validation/files/13165294/bios-lock_log.zip)
[smm-bios-write-protection_log.zip](https://github.com/Dasharo/open-source-firmware-validation/files/13166061/smm-bios-write-protection_log.zip)
[usb-stack_log.zip](https://github.com/Dasharo/open-source-firmware-validation/files/13166063/usb-stack_log.zip)

Fixes are in preparation:
https://github.com/Dasharo/open-source-firmware-validation/pull/55/

**Comment by Psotas** [comment]
[smm-bios-write-protection_log.zip](https://github.com/Dasharo/open-source-firmware-validation/files/13263809/smm-bios-write-protection_log.zip)
Still some problem with `SMM002.001 SMM BIOS write protection disabling (Ubuntu 22.04)` on VP2420
```
SMM002.001 SMM BIOS write protection disabling (Ubuntu 22.04) :: S... | FAIL |
No match found for 'to boot directly' in 30 seconds. Output:
                /---------------------------------------------\
                |Configuration changed. Reset to apply it Now.|
                |            Press ENTER to reset             |
                \---------------------------------------------/
```

**Comment by macpijan** [comment]
@Psotas The other ones has been fixed in the main branch already?

 Have you tried running the test multiple times with the same results?

**Comment by macpijan** [comment]
The problems shall be resolved by: https://github.com/Dasharo/open-source-firmware-validation/pull/81 which provides keywords with better reliability in terms of parsing menus

**Comment by Psotas** [comment]
@macpijan 

> The other ones has been fixed in the main branch already?

Yes, it works, only with https://github.com/Dasharo/open-source-firmware-validation/issues/36#issuecomment-1794240906 I noticed problems.

> Have you tried running the test multiple times with the same results?

I will check it when the vp4670 v2 platform is available.
