### ISSUE TITLE
automatic DCU test suite FAILS| protectli v1210|Dasharo 0.9.2 

### ISSUE THREAD

**Issue by wiktormowinski** [Dasharo/open-source-firmware-validation#367]
### Device

v1210

### RTE version

0.7.5

### OSFV version

branch: regression_protectli_v121x, commit 850960371517cbb5dab6f24b1b9c6d8dda23778c

### Brief summary

DCU 001&2.001 FAIL with the prompt of a missing keyword and DCU003.001 cannot find a specific String while performing the test automatically

### How reproducible

happens every time

### How to reproduce

Run dcu test suite (or any individual test case) on protetcli v1210 with dasharo 0.9.2 firmware

### Expected behavior

the test should run just like his manual counterpart

### Actual behavior

-missing uuid4 keyword in DCU001.001
-missing Random Int keyword in DCU002.001
-DCU003.001 is unable to recognize 'Success' string

### Link to screenshots or logs

[dasharo-compatibility_.zip](https://github.com/user-attachments/files/16162332/dasharo-compatibility_.zip)

**Comment by macpijan** [comment]
Should be fixed by this commit: https://github.com/Dasharo/open-source-firmware-validation/pull/361/commits/04e410031775b1ee51d8b9c97915d27696856bb8

```
DEVICE_IP=192.168.10.252 FW_FILE=protectli_v1210_v0.9.2.rom RTE_IP=192.168.10.55 CONFIG=protectli-v1210 SNIPEIT_NO=true ./scripts/run.sh dasharo-compatibility/dcu.robot
==============================================================================
Dcu                                                                           
==============================================================================
DCU001.001 Change the UUID :: This test case verifies that the UUI... | PASS |
------------------------------------------------------------------------------
DCU002.001 Change the serial number :: This test case verifies tha... | PASS |
------------------------------------------------------------------------------
DCU003.001 Change the bootsplash logo :: This test case verifies t... | PASS |
------------------------------------------------------------------------------
DCU004.001 Verify SMMSTORE changes :: This test case verifies that... | SKIP |
smmstoretool ins not yet supported in DCU
------------------------------------------------------------------------------
Dcu                                                                   | PASS |
4 tests, 3 passed, 0 failed, 1 skipped
==============================================================================
```
