### ISSUE TITLE
Missing hotkey tests for Windows

### ISSUE THREAD

**Issue by mkopec** [Dasharo/open-source-firmware-validation#370]
### Device

NovaCustom laptops

### RTE version

n/a

### OSFV version

9603436e11cf52ab699fe4e928cdb6acb106198a

### Affected component(s) or functionality

EC / input device tests

### Brief summary

There are no tests for function keys on Windows

### How reproducible

100%

### How to reproduce

- open https://docs.google.com/spreadsheets/d/1wSE6xA3K3nXewwLn5lV39_2wZL1kg5AkGb4mvmG3bwE/edit?gid=1742235393#gid=1742235393
- look for brightness hotkey tests for Windows

### Expected behavior

- There are hotkey tests for Windows

### Actual behavior

- There are no hotkey tests for Windows

### Link to screenshots or logs

https://docs.google.com/spreadsheets/d/1wSE6xA3K3nXewwLn5lV39_2wZL1kg5AkGb4mvmG3bwE/edit?gid=1742235393#gid=1742235393

**Comment by philipandag** [comment]
@mkopec I have added the missing ECR tests related to function keys in windows to the [Matrix](https://docs.google.com/spreadsheets/d/1wSE6xA3K3nXewwLn5lV39_2wZL1kg5AkGb4mvmG3bwE/edit?gid=1742235393#gid=1742235393) and copied the test statuses similarly to the brightness up/down tests.
