### ISSUE TITLE
VP6650 tests can't install required software

### ISSUE THREAD

**Issue by philipandag** [Dasharo/open-source-firmware-validation#371]
### Device

VP6650

### RTE version

d45acd2253d9

### OSFV version

f65343f6ee8b

### Affected component(s) or functionality

The CPU-core-count test TPM support test suites,  the process of downloading `cpuid` and `tpm2-tools`

### Brief summary

The test supposedly downloads the package then fails because it is not found

### How reproducible

Every time if required package is not installed prior

### How to reproduce

Run any `CCC` test using cpuid, like:
`robot -L TRACE -v rte_ip:192.168.10.14 -v device_ip:192.168.10.156 
-v sonoff_ip:192.168.10.119  -v config:protectli-vp6650 -t "CCC003*" dasharo-compatibility/cpu-cores-count.robot`

or  a `TPM` test:
`robot -L TRACE -v rte_ip:192.168.10.14 -v device_ip:192.168.10.156 
-v sonoff_ip:192.168.10.119  -v config:protectli-vp6650 -t "TPM001*" dasharo-security/tpm-support.robot`

### Expected behavior

The `cpuid` or `tpm2-tools` should be installed and the test should pass

### Actual behavior

The test fails because `cpuid` and `tmp2-tools` package is not installed despite the test saying it has installed the package.

### Link to screenshots or logs

Logs: https://cloud.3mdeb.com/index.php/s/RLyC3Sir4Fqtn55
```
==============================================================================
Cpu-Cores-Count                                                               
==============================================================================
CCC003.001 Check core count (HT Enabled, P: All, E: 0) (Ubuntu)       .       
Checking if cpuid is installed...

Package cpuid is not installed

Installing required package (cpuid)...

Required package (cpuid) installed successfully
CCC003.001 Check core count (HT Enabled, P: All, E: 0) (Ubuntu)       | FAIL |
'Command 'cpuid' not found, but can be installed with:
apt install cpuid
0' cannot be converted to an integer: ValueError: invalid literal for int() with base 10: "command'cpuid'notf
ound,butcanbeinstalledwith:aptinstallcpuid0"
-----------------------------------------------------------------------------
```

```
------------------------------------------------------------------------------
TPM001.002 TPM Support (Ubuntu) :: Check whether the TPM is initia... .....
Checking if tpm2-tools is installed...

Package tpm2-tools is not installed

Installing required package (tpm2-tools)...

Required package (tpm2-tools) installed successfully
TPM001.002 TPM Support (Ubuntu) :: Check whether the TPM is initia... | FAIL |
'Command 'tpm2_pcrread' not found, but can be installed with:
apt install tpm2-tools' does not contain 'sha1:'
------------------------------------------------------------------------------
```

**Comment by macpijan** [comment]
Following diff might help here:

```
diff --git a/keywords.robot b/keywords.robot
index 1a8dafef06d5..e5e45c5925e3 100644
--- a/keywords.robot
+++ b/keywords.robot
@@ -1298,7 +1298,7 @@ Detect Or Install Package
     Install Package    ${package}
     Sleep    10s
     ${is_package_installed}=    Check If Package Is Installed    ${package}
-    IF    ${is_package_installed}=='False'
+    IF    not ${is_package_installed}
         FAIL    \nRequired package (${package}) cannot be installed
     END
     Log To Console    \nRequired package (${package}) installed successfully
```

**Comment by macpijan** [comment]
On top of that, you had network error in the log:

```
 	Return: "Reading package lists... Done\nBuilding dependency tree... Done\nReading state information... Done\nThe following package was automatically installed and is no longer required:\n  libsysmetrics1\nUse 'sudo apt autoremove' to remove it.\nThe following NEW packages will be installed:\n  cpuid\n0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.\nNeed to get 104 kB of archives.\nAfter this operation, 443 kB of additional disk space will be used.\nIgn:1 http://pl.archive.ubuntu.com/ubuntu jammy/universe amd64 cpuid amd64 20211210-1\nIgn:1 http://pl.archive.ubuntu.com/ubuntu jammy/universe amd64 cpuid amd64 20211210-1\nIgn:1 http://pl.archive.ubuntu.com/ubuntu jammy/universe amd64 cpuid amd64 20211210-1\nErr:1 http://pl.archive.ubuntu.com/ubuntu jammy/universe amd64 cpuid amd64 20211210-1\n  Temporary failure resolving 'pl.archive.ubuntu.com'\nE: Failed to fetch http://pl.archive.ubuntu.com/ubuntu/pool/universe/c/cpuid/cpuid_20211210-1_amd64.deb  Temporary failure resolving 'pl.archive.ubuntu.com'\nE: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?"
```

**Comment by macpijan** [comment]
@BeataZdunczyk Proposed some hints already how to resolve this

**Comment by philipandag** [comment]
> Following diff might help here:
> 
> ```
> diff --git a/keywords.robot b/keywords.robot
> index 1a8dafef06d5..e5e45c5925e3 100644
> --- a/keywords.robot
> +++ b/keywords.robot
> @@ -1298,7 +1298,7 @@ Detect Or Install Package
>      Install Package    ${package}
>      Sleep    10s
>      ${is_package_installed}=    Check If Package Is Installed    ${package}
> -    IF    ${is_package_installed}=='False'
> +    IF    not ${is_package_installed}
>          FAIL    \nRequired package (${package}) cannot be installed
>      END
>      Log To Console    \nRequired package (${package}) installed successfully
> ```
> 
> The `Check If Package Is Installed` returns bool, not string

That's right, at least now robot realises the package was not installed.

**Comment by philipandag** [comment]
> On top of that, you had network error in the log:
> 
> ```
>  	Return: "Reading package lists... Done\nBuilding dependency tree... Done\nReading state information... Done\nThe following package was automatically installed and is no longer required:\n  libsysmetrics1\nUse 'sudo apt autoremove' to remove it.\nThe following NEW packages will be installed:\n  cpuid\n0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.\nNeed to get 104 kB of archives.\nAfter this operation, 443 kB of additional disk space will be used.\nIgn:1 http://pl.archive.ubuntu.com/ubuntu jammy/universe amd64 cpuid amd64 20211210-1\nIgn:1 http://pl.archive.ubuntu.com/ubuntu jammy/universe amd64 cpuid amd64 20211210-1\nIgn:1 http://pl.archive.ubuntu.com/ubuntu jammy/universe amd64 cpuid amd64 20211210-1\nErr:1 http://pl.archive.ubuntu.com/ubuntu jammy/universe amd64 cpuid amd64 20211210-1\n  Temporary failure resolving 'pl.archive.ubuntu.com'\nE: Failed to fetch http://pl.archive.ubuntu.com/ubuntu/pool/universe/c/cpuid/cpuid_20211210-1_amd64.deb  Temporary failure resolving 'pl.archive.ubuntu.com'\nE: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?"
> ```

And that is the issue here. It seems like for some reason when the installation is preformed by robot it fails because of fail in name resolution. Although when I copy&paste the exact command that is sent via serial  the package installs succesfully every time.

**Comment by macpijan** [comment]
> Although when I copy&paste the exact command that is sent via serial the package installs succesfully every time.

It is most likely a timing problem, try waiting for network to become available prior downloading packages.

**Comment by philipandag** [comment]
More curiously, after a couple attempts it seems that the problem vanished and the packages are being installed succesfully

**Comment by philipandag** [comment]
> It is most likely a timing problem, try waiting for network to become available prior downloading packages.
It may be just it. Maybe the device needs a little more time to get the nameservers from dhcp. I will try that.

**Comment by philipandag** [comment]
I will run the test a couple times in a loop and see if it is more stable with a little bit of delay before installing the package.

**Comment by macpijan** [comment]
> if it is more stable with a little bit of delay before installing the package.

More preferably, add a keyword checking for network connection. Perhaps we already have one.

**Comment by macpijan** [comment]
Something like

```
    Wait Until Keyword Succeeds    5x    1s
    ...    Check Internet Connection On Linux
```

**Comment by philipandag** [comment]
I have tested installing after reboot then uninstalling the `cpuid` package in loop for 10 times and it did not fail once. Seems it doesn't happen that often, but when it was happening it was consistent for some time. I will try adding your suggestion and running a longer test.

**Comment by philipandag** [comment]
Now that is unfortunate
```
STR001.001 Test :: Testing if Detect Or Install Package kw is stable  | FAIL |
Keyword 'Check Internet Connection On Linux' failed after retrying 10 times. The last error was: 'ping: google-public-dns-a.google.com: Temporary failure in name resolution' does not contain ', 0% packet loss'
```
It seems sometimes the device sometimes doesn't login to the network even after over 10s

**Comment by philipandag** [comment]
pr: https://github.com/Dasharo/open-source-firmware-validation/pull/400
