### ISSUE TITLE
Problem with Wifi scanning| test case id: [WLE002.001]|Protectli Vault jsl v1210| Dasharo 0.9.2|Ubuntu

### ISSUE THREAD

**Issue by wiktormowinski** [Dasharo/open-source-firmware-validation#372]
### Device

Protectli Vault jsl v1210

### RTE version

0.7.5

### OSFV version

branch: regression_protectli_v121x, commit 8509603

### Brief summary

1210 doesn't see wifi card in test case WLE002.001

### How to reproduce

-power on
-boot the device in Ubuntu os
-login
-type in terminal:
```
nmcli dev wifi rescan
```
and
```
nmcli dev wifi list
```

### Expected behavior

the {3_MDEB_WIFI_NETWORK} should be seen

### Actual behavior

```
user@3mdeb:~$ nmcli dev wifi rescan
Error: No Wi-Fi device found.
```

### Link to screenshots or logs

[WLE002.001 LOGS.zip](https://github.com/user-attachments/files/16180895/WLE002.001.LOGS.zip)

### Additional context

There is some evidence that wifi should work:

1. The alternate procedure for Windows (under test case WLE002.002) works
2.  you can list devices with commands such as:

```
nmcli con
```
```
ip a
```
or
```
lspci | grep "Network controller:"

```
and they all return the correct output as expected

### Solutions you've tried

i tried to set the connection with this command, but to no avail:
```
user@3mdeb:~$ sudo nmcli connection up e1419a5e-5e1d-3fff-a17c-b2fc6d2cef99
Connection successfully activated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/3)
```

**Comment by macpijan** [comment]
It works, simply the OS has not been prepared properly.

if you look up logs in `dmesg`, it shows:

```
[  724.952928] ath10k_pci 0000:04:00.0: pci irq msi oper_irq_mode 2 irq_mode 0 reset_mode 0
[  725.165910] ath10k_pci 0000:04:00.0: qca6174 hw3.0 target 0x05020000 chip_id 0x003409ff sub 168c:3361
[  725.165937] ath10k_pci 0000:04:00.0: kconfig debug 0 debugfs 1 tracing 1 dfs 0 testmode 0
[  725.167472] ath10k_pci 0000:04:00.0: firmware ver WLAN.RM.4.4.1-00309- api 6 features wowlan,ignore-otp,mfp crc32 0793bcf2
[  725.234160] ath10k_pci 0000:04:00.0: board_file api 2 bmi_id N/A crc32 d2863f91
[  732.489767] ath10k_pci 0000:04:00.0: wmi unified ready event not received
[  732.523891] ath10k_pci 0000:04:00.0: device has crashed during init
[  732.545996] ath10k_pci 0000:04:00.0: device has crashed during init
[  732.546014] ath10k_pci 0000:04:00.0: failed to wait for target init: -70
[  732.548852] ath10k_pci 0000:04:00.0: could not init core (-110)
[  732.548896] ath10k_pci 0000:04:00.0: could not probe fw (-110)
```

If you put these erros in dasharo-issues search bar, you can find: https://github.com/Dasharo/dasharo-issues/issues/595#issuecomment-1989012333
