### ISSUE TITLE
Dasharo Compatibility: Network boot test does not get expected output

### ISSUE THREAD

**Issue by johanes2115** [Dasharo/open-source-firmware-validation#38]
PXE004.001: DTS option is available and works correctly gets:

`Waiting for link-up on net0...... ok 
Configuring (net0 d4:93:90:16:94:92).......... ok 
http://boot.3mdeb.com/dts.ipxe... ok
http://boot.3mdeb.com/dasharo/bzImage-v1.2.8... ok 
http://boot.3mdeb.com/dasharo/dts-base-image-v1.2.8.cpio.gz... ok`

Instead of:

`Enter an option`

PXE006.001: iPXE shell option is available and works correctly gets:

`You are now in iPXE shell. Type "exit" to go back to the main menu.`

Instead of:

`iPXE>`

Both funcionalities work fine when tested manually. Tested on Novacustom laptops on branch `novacustom-wip`.

**Comment by macpijan** [comment]
Not reproduced recently
