### ISSUE TITLE
Dasharo Stability: NVMe detection test does not get expected output

### ISSUE THREAD

**Issue by johanes2115** [Dasharo/open-source-firmware-validation#39]
SNV0004.001 NVMe detection after suspension (Ubuntu 22.04) gets SOL string as output instead of login prompt. Tested on Novacustom nv41 ADL. Branch `novacustom-wip`.

**Comment by macpijan** [comment]
The problem is, there would be no login prompt from Linux ever in the current setup, as the serial over EC transmits only UEFI menus. It is not a **real** serial port.

**Comment by macpijan** [comment]
Not reproduced recently
