### ISSUE TITLE
Dasharo Performance: coreboot boot measure test fails to authenticate

### ISSUE THREAD

**Issue by johanes2115** [Dasharo/open-source-firmware-validation#41]
All of the test cases get:

`Authentication failed for user 'root'.`

The test seem to be hardcoded to Debian.

Tested on Novacustom nv41 ADL. Branch `novacustom-wip`.

**Comment by BeataZdunczyk** [comment]
@johanes2115 is this a test-related issue? Does the manual test pass? What is the expected behavior?
@macpijan cc

**Comment by johanes2115** [comment]
@BeataZdunczyk is certainly is test related issue, added some additional info.

**Comment by macpijan** [comment]
This suite does not use debian anymore, so not a problem
