### ISSUE TITLE
Dasharo Performance: CPU frequency measure multiple fails

### ISSUE THREAD

**Issue by johanes2115** [Dasharo/open-source-firmware-validation#43]
CPF001.001 CPU not stuck on initial frequency (Ubuntu 22.04) returns:

`IndexError: Given index 0 is out of the range 0--1.`

CPF004.001 CPU with load runs on expected frequency (Ubuntu 22.04) fails to authenticate:

`Keyword 'SSHLibrary.Login' failed after retrying 12 times. The last error was: Authentication failed for user 'ubuntu'.`

CPF002.002, CPF003.002, CPF004.002, CPF005.002 CPU / CPU with load runs on expected frequency (Windows 11)  fail to convert string to number, return:

`>> > (Get-CimInstance CIM_Processor).MaxClockSpeed*((Get-Counter -Counter "\Processor Information(_Total)\% Processor Performance").CounterSamples.CookedValue) >> > (Get-CimInstance CIM_Processor).MaxClockSpeed*((Get-Counter -Counter "\Processor Information(_Total)\% Processor Performance").CounterSamples.CookedValue)/100 >> 1448.28099173554' cannot be converted to a floating point number: ValueError: could not convert string to float: '>> > (Get-CimInstance CIM_Processor).MaxClockSpeed*((Get-Counter -Counter "\\Processor Information(_Total)\\% Processor Performance").CounterSamples.CookedValue)\r\n>> > (Get-CimInstance CIM_Processor).MaxClockSpeed*((Get-Counter -Counter "\\Processor Information(_Total)\\% Processor Performance").CounterSamples.CookedValue)/100\r\n>> \r\n1448.28099173554`

Additionally, the test bases on base clock speed, which will be lower than actual measured clock speed.

Tested on Novacustom nv41 ADL. Branch `novacustom-wip`.

**Comment by Psotas** [comment]
[cpu-frequency_log.zip](https://github.com/Dasharo/open-source-firmware-validation/files/13249973/cpu-frequency_log.zip)
Same problem on _MSI® PRO Z690-A DDR4_
Dasharo v1.1.3

**Comment by macpijan** [comment]
In general, the fix is supposed to be integrated here already: https://github.com/Dasharo/open-source-firmware-validation/pull/361
It can be checked together with previous ticket on CPU temp, on MSI @BeataZdunczyk

**Comment by philipandag** [comment]
The errors from this issue are fixed on the current develop branch. Tested on a NV50MB (ubuntu) and V560TND (Ubuntu, Windows).

**Comment by philipandag** [comment]
[ubuntu-with-load_log.zip](https://github.com/user-attachments/files/16778740/ubuntu-with-load_log.zip)
[ubuntu-not-stuck_log.zip](https://github.com/user-attachments/files/16778750/ubuntu-not-stuck_log.zip)
[windows-under-load_log.zip](https://github.com/user-attachments/files/16778824/windows-under-load_log.zip)
The tests were forcibly ended prematurely when it was possible to determine if they work.
