### ISSUE TITLE
Dasharo Performance: Custom fan curve fails to connect with the DUT

### ISSUE THREAD

**Issue by johanes2115** [Dasharo/open-source-firmware-validation#44]
Both test cases return:

`Keyword 'SSHLibrary.Login' failed after retrying 12 times. The last error was: NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 192.168.4.240`

Tested on Novacustom nv41 ADL. Branch `novacustom-wip`.

**Comment by macpijan** [comment]
outdated
