### ISSUE TITLE
Dasharo Performance: Platform stability does not get correct output

### ISSUE THREAD

**Issue by johanes2115** [Dasharo/open-source-firmware-validation#46]
STB001.001Verify if no reboot occurs in the firmware waits for `LOCAL`, but instead gets:

`Press ESC in 4 seconds to skip startup.nsh or any other key to continue.`

STB001.003 Verify if no reboot occurs in the OS (Windows 11)  gets incorrect output, which then can not be converted into integer:

`>> > Get-NetAdapter -Name "Ethernet*"
>> 

Name                      InterfaceDescription                    ifIndex Status       MacAddress             LinkSpeed
...`

`:' cannot be converted to a floating point number: ValueError: could not convert string to float: ':`

Tested on Novacustom nv41 ADL. Branch `novacustom-wip`.

**Comment by macpijan** [comment]
outdated
