### ISSUE TITLE
V560TNE v0.9.1-rc3 touchpad on/off function key not working

### ISSUE THREAD

**Issue by philipandag** [Dasharo/open-source-firmware-validation#472]
### Device

V560TNE

### RTE version

--

### OSFV version

develop

### Affected component(s) or functionality

turning touchpad on/off using function key

### Brief summary

touchpad on/off function key it not working

### How reproducible

100%

### How to reproduce

press fn+F1

### Expected behavior

should turn touchpad on/off

### Actual behavior

the touchpad works

### Link to screenshots or logs

manual visual test, no logs

### Solutions you've tried

tried using `libinput debug-events --show-keycodes` but is does not show any event

**Comment by mkopec** [comment]
ah, we need to add a quirk to udev for this model too

**Comment by philipandag** [comment]
This works fine on Windows
