### ISSUE TITLE
V540TND v0.9.1-rc5 relatively long boot times

### ISSUE THREAD

**Issue by philipandag** [Dasharo/open-source-firmware-validation#535]
### Component

Dasharo firmware

### Device

NovaCustom V54 14th Gen

### Dasharo version

v0.9.1-rc5

### Dasharo Tools Suite version

develop

### Test case ID

CBMEM002, CBMEM003

### Brief summary

Very long boot times, exceeding the limits given in platform configs

### How reproducible

I have only run the suite once.

### How to reproduce

Run CBMEM tests via osfv

### Expected behavior

Average boot times should be < 10s.

### Actual behavior

 In this case most are ~7-8s but because of a large spike on the first boot time the average warmboot time exceeded 10s.

### Screenshots

[dasharo-performance_log.zip](https://github.com/user-attachments/files/16989613/dasharo-performance_log.zip)

### Additional context

I have seen large boot time spikes on the first measurement before. Maybe it's an error in measurements?

**Comment by wiktormowinski** [comment]
https://github.com/Dasharo/open-source-firmware-validation/pull/538 done, the new version skips the first measurement
