### ISSUE TITLE
MSI Bluetooth scanning returns no results in Ubuntu

### ISSUE THREAD

**Issue by JanPrusinowski** [Dasharo/open-source-firmware-validation#548]
### Component

Dasharo firmware

### Device

MSI Pro Z690-A

### Dasharo version

1.1.4-rc1

### Dasharo Tools Suite version

develop

### Test case ID

WLE003.001

### Brief summary

MSI Bluetooth scanning returns no results in Ubuntu

### How reproducible

100%

### How to reproduce

On DUT in Ubuntu write to terminal: `bluetoothctl power on` then `bluetoothctl scan on`

### Expected behavior

There should be an output stating: `Discovery started` and then list of devices

### Actual behavior

`SetDiscoveryFilter success` is displayed and nothing else

### Screenshots

[log.zip](https://github.com/user-attachments/files/17407908/log.zip)
![image](https://github.com/user-attachments/assets/d9479635-3abd-4033-9259-938bea83000a)

**Comment by wiktormowinski** [comment]
resolved: https://github.com/Dasharo/open-source-firmware-validation/pull/549#discussion_r1812349485
