### ISSUE TITLE
WLE001.002 can't detect wifi card in Windows

### ISSUE THREAD

**Issue by JanPrusinowski** [Dasharo/open-source-firmware-validation#552]
### Device

Protectli VP3230

### RTE version

-

### OSFV version

develop

### Affected component(s) or functionality

WLE001.002 test

### Brief summary

WLE001.002 cant detect wifi card in Windows

### How reproducible

100%

### How to reproduce

Run WLE001.002  test on VP3230: `robot -v snipeit:no -L TRACE -v rte_ip:192.168.10.35 -v config:protectli-vp3230 -v sonoff_ip:192.168.10.27 -v device_ip:192.168.10.40 -t 'WLE001.002*' -v fw_file:./protectli_vp32xx_v0.9.0_rc2.rom dasharo-compatibility/wifi-bluetooth-support.robot`

### Expected behavior

Test passes

### Actual behavior

Test fails

### Link to screenshots or logs

[log.zip](https://github.com/user-attachments/files/17506879/log.zip)

### Additional context

if you run `ipconfig /all` card is listed: `Qualcomm Atheros QCA61x4A Wireless Network Adapter`. If you runt `WLE002.002` then actually networks are found. However this test is unable to verify existence of this card in the platform. This test might need a change in approach to check if the wifi contorller is present.

**Comment by SebastianCzapla** [comment]
Fixed in https://github.com/Dasharo/open-source-firmware-validation/pull/631
