### ISSUE TITLE
Duplicate keywords

### ISSUE THREAD

**Issue by m-iwanicki** [Dasharo/open-source-firmware-validation#591]
### Device

-

### RTE version

-

### OSFV version

develop

### Brief summary

There are duplicate keywords defined

### How reproducible

100%

### How to reproduce

build docs via `./scripts/create-docs.sh` run `firefox docs/index.html` and search for `Creating keyword failed: Keyword with same name defined multiple times.` string

### Expected behavior

No duplicates, keyword documentation in docs

### Actual behavior

Multiple duplicated keywords:

* Boot System Or From Connected Disk
* Get UEFI Boot Manager Entries
* Get UEFI Option
* Login To Windows
* Login To Windows Via SSH
* Measure Coldboot Time
* Measure Reboot Time
* Measure Warmboot Time
* Reset UEFI Options To Defaults
* Set UEFI Option

and `Creating keyword failed: Keyword with same name defined multiple times.` error in documentation

### Link to screenshots or logs

![image](https://github.com/user-attachments/assets/7a0ba6c8-53b7-4509-a8ce-18a4c2bd5c23)

**Comment by EduKav1813** [comment]
@m-iwanicki This was fixed with https://github.com/Dasharo/open-source-firmware-validation/pull/596
