### ISSUE TITLE
Reset to default in submenu works on whole menu `Dasharo System Features`, not only for value in submenu.

### ISSUE THREAD

**Issue by Psotas** [Dasharo/open-source-firmware-validation#72]
### Device

MSI® PRO Z690-A DDR4 

### RTE version

Dasharo v1.1.3

### Affected component(s) or functionality

Reset to default in submenu works on whole menu `Dasharo System Features`, not only for value in submenu.

### Brief summary

Reset to default in submenu works on whole menu `Dasharo System Features`, not only for value in submenu.

### How to reproduce

Press F9 in submenu in `Dasharo System Features`.

### Expected behavior

Reset value only in submenu.

### Actual behavior

Reset value in whole ``Dasharo System Features` menu.

### Link to screenshots or logs

-

### Additional context

For example, when I try to change the default value for `Intel ME mode` in the `Intel Managment Engine Options` submenu, it also restores the default value for `Enable Serial Port` in the `Serial Port Configuration` submenu.

In `Device Manager` it works correctly, reset to default works only for current submenu.

**Comment by macpijan** [comment]
This was a FW issue https://github.com/Dasharo/dasharo-issues/issues/355 and is already solved.
