### ISSUE TITLE
Missing default values in `Device Manager`.

### ISSUE THREAD

**Issue by Psotas** [Dasharo/open-source-firmware-validation#73]
### Device

MSI® PRO Z690-A DDR4

### RTE version

Dasharo v1.1.3

### Brief summary

ost submenus in `Device Manager` are missing default values. F9 doesn't change anything.

### How to reproduce

F9 in `Device Manager` submenus.

### Expected behavior

Reset to default value.

### Actual behavior

F9 does not change anything in most `Device Manager` submenus.

In `TCG2 Configuration` it resets `Attempt TPM Device` to `<TPM 1.2>`. But after flashing, the default value is `<TPM 2.0>`

### Link to screenshots or logs

-

**Comment by macpijan** [comment]
Fixed by a FW change: https://github.com/Dasharo/dasharo-issues/issues/355
