### ISSUE TITLE
Fail when converting whitespace to an integer value in `cpu-status.robot` tests

### ISSUE THREAD

**Issue by Psotas** [Dasharo/open-source-firmware-validation#76]
### Device

MSI® PRO Z690-A DDR4

### RTE version

Dasharo v1.1.3

### Brief summary

Fail when converting whitespace to an integer value in `cpu-status.robot` tests

### How to reproduce

Run `CPU002.001 CPU cache enabled (Ubuntu 22.04)` test

### Expected behavior

Test Pass

### Actual behavior

RuntimeError: '      ' cannot be converted to an integer: ValueError: invalid literal for int() with base 10: ''

### Link to screenshots or logs

[cpu-status_log.zip](https://github.com/Dasharo/open-source-firmware-validation/files/13202845/cpu-status_log.zip)

**Comment by macpijan** [comment]
not reproducible recently
