### ISSUE TITLE
Parse coreboot config to check for expected features

### ISSUE THREAD

**Issue by macpijan** [Dasharo/open-source-firmware-validation#82]
### The problem you're addressing (if any)

We could check the coreboot cofnig from binary to see which features should be expected to enabled, or what the default values should be.

### Additional context

See discussion here: https://github.com/Dasharo/open-source-firmware-validation/pull/29/#discussion_r1352083455

**Comment by macpijan** [comment]
@BeataZdunczyk Maybe a bit more complex, but could be another step in generating configs automatically - to detect which features should be enabled, and which test matrix should be applied for the given hardware.

So related to feature/test matrix topics as well.

**Comment by filipleple** [comment]
Base mechanism with some example options implemented in https://github.com/Dasharo/open-source-firmware-validation/pull/392. It works, the list of available `option:test_flag` pairs would ideally be constantly extended.
