### ISSUE TITLE
Separate S3 and S0ix tests

### ISSUE THREAD

**Issue by mkopec** [Dasharo/open-source-firmware-validation#91]
### The problem you're addressing (if any)

Right now the test cases don't specify which sleep mode should be tested.

### Describe the solution you'd like

Sleep test cases should be split into separate S0ix and S3 cases / variants.

### Where is the value to a user, and who might that user be?

we know exactly which sleep type was tested

**Comment by macpijan** [comment]
@BeataZdunczyk I think @mkopec will be a better one to judge on status and importance here

**Comment by mkopec** [comment]
This is basically done at this point I believe.
